server:
  port: 8081

spring.rocketmq:
  namesrv-addr: n1.rocketmq.innermail.com:9876
  producer-group: temail-dispatcher-producer
  consumer-group: temail-dispatcher-consumer-x
  consumer-topic: temail-notification
  push-topic: temail-push-offline-message push-tag: '*'

app:
  dispatcher:
    auth-verify-url: http://auth.innermail.com:8081/verify
    temail-channel-url: http://channel.innermail.com:8081/locations/{accountNo}
    http-cliet:
      connect-timeout-in-milli: 3000
      read-timeout-in-milli: 3000
