server:
  port: 8888

temail.cdtp.dispatcher:
  cmd-request-map:
    usermailGet:
      url: http://192.168.15.186:8090/usermail
      method: GET
    usermailPost:
      url: http://192.168.15.186:8090/usermail
      method: POST
    revertPut:
      url: http://192.168.15.186:8090/revert
      method: PUT
  auth-verify-url: http://192.168.15.186:8081/verify
  rocketmq:
    namesrvAddr: 172.28.43.18:9876
    producerGroup: cdtp-dispatcher-producer
    consumerGroup: cdtp-dispatcher-consumer
    topic: cdtp-notify
