server:
  port: 8081
temail:
  dispatcher:
    rocketmq:
      producer-group: temail-dispatcher-producer
      consumer-group: temail-dispatcher-consumer
      consumer-topic: temail-notification

swagger:
  contact:
    name: 姚华成
    email:  yaohuacheng@syswin.com
  title: temail-dispatcher
  description: CDTP分发服务
  basePath: /**
